Core of Hot Desking API Service
ohalushchak-exadel/internship-team4 pull request #1
Opened 2022-02-07 08:12 UTC by gargatuma

All essential entities are created and packaged on basis of their feature. Also their corresponding repositories, services, and controllers are present with basic responses for get and post commands

2022-02-07 09:23 UTC, ohalushchak-exadel requested changes

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/user/UserEntity.java
> +public class UserEntity {
same comments as for the other entities

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/user/UserService.java
> +        return ResponseEntity.notFound().build();
same as for the other services

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/VacationController.java
> +@Controller
`@RestController`

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/VacationController.java
> +@RequestMapping(path = "api/vacation")
what is `api` for?

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/VacationEntity.java
> +public class VacationEntity {
same as for the other entities

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkspaceController.java
> +public class WorkspaceController {
same as for the other controllers

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkspaceEntity.java
> +public class WorkspaceEntity {
same as for other entities

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkspaceService.java
> +        return ResponseEntity.notFound().build();
same as for other services

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/application.properties
> +spring.liquibase.enabled=true
add newline at the end of all files

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/01-create-office.yaml
> +#              tableName: office
this was good, add it to the changeset below

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/02-create-floor-plan.yaml
> +        - createTable:
`tableExists` precondition

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/03-create-workspace.yaml
> +        - createTable:
`tableExists` precondition

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +        - createTable:
`tableExists` precondition

2022-02-07 09:23 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/07-create-waitinglist.yaml
> +            tableName: waitinglist
`tableExists` precondition

`waiting_list`

2022-02-07 09:49 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/user/UserEntity.java
> +    @ManyToOne
Could It be ManyToMany, e.g. when the User books 2 different workstations?

2022-02-07 10:04 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        System.out.println(office);
Get rid of System.out.println. Use logger instead.

2022-02-07 10:13 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/workspace/WorkspaceEntity.java
> +    private Boolean hasPc;
In this case autogenerated getter will be named isHasPc(). It looks odd. 
Try to think of more situable names for  'has***' fields. E.g. withPc or something like that.

2022-02-07 18:34 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +@RequestMapping(path = "api/booking")
Most of the services provided user api url, like telegram bot api so I decided it's good Idea to add api in url path. Should I remove it?

2022-02-07 18:35 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +    @GetMapping(path = "{id}")
But it works without backslash. Why to add it? Just convention?

2022-02-07 18:36 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingEntity.java
> +public class BookingEntity {
Why do we need explicitly declare them when they can be inferred by hibernate

2022-02-07 19:05 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +@RequestMapping(path = "api/booking")
if you want to add it everywhere, just use `server.servlet.context-path: ` config property

2022-02-07 19:05 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +    @GetMapping(path = "{id}")
yes, it's optional but makes it a bit easier to understand

2022-02-07 19:10 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/BookingEntity.java
> +public class BookingEntity {
hibernate doesn't always generate the names you actually use in the database, so you have to mark them with `@Column` with a proper name. And if you mark only one, it'll be confusing

2022-02-07 19:10 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +@RequestMapping(path = "api/office")
removed

2022-02-07 19:11 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +    @PostMapping(path = "add")
ok

2022-02-07 19:42 UTC, gargatuma commented on src/main/resources/application.properties
> +spring.liquibase.enabled=true
ok. but why?

2022-02-07 20:16 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingEntity.java
> +public class BookingEntity {
ok

2022-02-07 20:17 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +@RequestMapping(path = "api/booking")
ok. But removed it. Do not think we need it now

2022-02-07 22:59 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/user/UserEntity.java
> +    @ManyToOne
This column denotes user's favorite workspace. User can have only one such workspace at a time

2022-02-07 23:00 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkspaceEntity.java
> +    private Boolean hasPc;
ok. This will be handled by other intern assigned to Floor-plan

2022-02-08 09:33 UTC, ohalushchak-exadel requested changes

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +    @ManyToOne
+ `@JoinColumn` ?

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +public class Booking {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +public class WaitingList {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +public class FloorPlan {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/Office.java
> +public class Office {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        System.out.println(id);
use logger instead

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +    FloorPlan create(FloorPlan floorPlan) {
public

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +    FloorPlan getById(UUID id) {
public

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/user/User.java
> +public class User {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/Vacation.java
> +public class Vacation {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/Vacation.java
> +    private User user;
Join?

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/Workspace.java
> +public class Workspace {
missing validation annotations

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/01-create-office.yaml
> +      id: create-office
create-office-**table**

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +      id: create-user
create-user-**table**

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +#                  defaultValueComputed: "gen_random_uuid()"
remove it if you don't need it

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +                  name: email
should be unique

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +                  type: varchar(10)
probably should be unique

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +                  type: varchar(10)
10 may not be enough

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/05-create-vacation.yaml
> +      id: create-vacation
create-vacation-**table**

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/05-create-vacation.yaml
> +#                  defaultValueComputed: "gen_random_uuid()"
remove if you don't need it

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/06-create-booking.yaml
> +      id: create-booking
create-booking-**table**

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/07-create-waiting-list.yaml
> +      id: create-waiting-list
create-waiting-list-**table**

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/07-create-waiting-list.yaml
> +#                  defaultValueComputed: "gen_random_uuid()"
remove

2022-02-08 09:33 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/07-create-waiting-list.yaml
add **-table** to each file name

2022-02-09 06:50 UTC, gargatuma commented on src/main/resources/db/changelog/changeset/04-create-user.yaml
> +                  type: varchar(10)
changed to 20

2022-02-09 12:22 UTC, ohalushchak-exadel requested changes

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/booking/WaitingList.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +    private Boolean hasConfRoom;
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/user/User.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/Vacation.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/Workplace.java
> +    @NotBlank
`@NotBlank` is used only for strings
you need `@NotNull` here

2022-02-09 13:52 UTC, merged