exceptions from office branch by Husan
ohalushchak-exadel/internship-team4 pull request #19
Opened 2022-02-16 13:18 UTC by KhusanKholmatov

new exceptions

2022-02-17 12:34 UTC, KhusanKholmatov commented
@viktarkolbik , @ohalushchak-exadel any comment??

2022-02-18 04:15 UTC, gargatuma requested changes

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/common/exception/ConflictException.java
> +}
missing new line at the end of file

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/common/exception/ErrorAdvice.java
> +}
missing new line at the end of file

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/common/exception/ForbiddenException.java
> +}
missing new line at the end of file

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/common/exception/NotFoundException.java
> +}
missing new line at the end of file

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +    @PostMapping("/{userId}")
Since we are going to use Spring Security {user_id} in url path is not necessary

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeService.java
> +        return officeResponse;
You need to user mapper for lines 28-38

2022-02-18 04:15 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeService.java
> +        Optional<Office> optionalOffice = officeRepository.findById(id);
You can use  .orElseThrow(() -> new NotFoundException() on this line. And remove isPresent condition below

2022-02-18 06:15 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +import com.exadel.coolDesking.common.exception.ConflictException;
not used import

2022-02-18 06:17 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        return ResponseEntity.status(200).body(new ArrayList(Arrays.asList(
Follow single style, use HttpStatus.XXX everywhere to setup status code.

2022-02-18 06:20 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeResponseMessage.java
> +public interface OfficeResponseMessage {
Don't use interface to store constants

https://www.baeldung.com/java-constants-good-practices

2022-02-18 06:24 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +    @GetMapping("/all")
just @GetMapping

2022-02-18 06:25 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeRepository.java
> +import javax.validation.constraints.NotBlank;
Remove not used imports

2022-02-18 09:01 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeRepository.java
> +import javax.validation.constraints.NotBlank;
done

2022-02-18 09:01 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +    @GetMapping("/all")
done

2022-02-18 09:01 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +import com.exadel.coolDesking.common.exception.ConflictException;
done

2022-02-18 09:05 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        return ResponseEntity.status(200).body(new ArrayList(Arrays.asList(
done

2022-02-18 10:45 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/common/exception/ErrorAdvice.java
> +}
done

2022-02-18 10:46 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/common/exception/NotFoundException.java
> +}
done

2022-02-18 10:46 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeService.java
> +        return officeResponse;
done

2022-02-18 11:01 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeService.java
> +        return officeResponse;
done

2022-02-18 11:38 UTC, closed without merging