Booking integrated into main!
ohalushchak-exadel/internship-team4 pull request #27
Opened 2022-02-20 10:31 UTC by Apulatjonov

2022-02-21 06:29 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +    private ModelMapper modelMapper() {
1. ModelMapper often has specific configuration for different domains, so reusing one instance in many situations can cause issues.
2. Why do you create a Bean, and then just call method _modelMapper()_? You newer reuse this bean so it's useless.
3. Do mapping work in separate class.

2022-02-21 06:34 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +        if (userRepository.findById(bookingDto.getUserId()).get().getRole().equals(UserRole.COMMON_USER)) {
Don't check access manually. 
@gargatuma is busy with Security, ask him for help

2022-02-21 06:35 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +        return new BookingResponseDTO(201, "Created", null);
Here and in other places
**201** and **"Created"** are useless. You must return it as status code of the Response.

2022-02-21 06:35 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +//    @NotNull
Drop useless comments.

2022-02-21 06:38 UTC, viktarkolbik commented on src/main/resources/application.properties
> +spring.datasource.username=postgres
don't change credentials

2022-02-21 06:50 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +        return new BookingResponseDTO(200, "OK", "Your booking has been successfully updated");
Convert updated entity into DTO and return it

2022-02-21 06:54 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +//        if (checkBooking(bookingDto)) {
Drop useless comment

2022-02-21 21:45 UTC, Apulatjonov commented
Everything mentioned above has been fixed!

2022-02-21 21:46 UTC, Apulatjonov commented on src/main/resources/application.properties
> +spring.datasource.username=aweasadbek
I need to change it for testing purpose

2022-02-22 06:09 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(bookingService.updateBooking(bookingDto, id));
For update operation return "OK" status

2022-02-22 06:11 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingRepository.java
> +import java.util.Date;
java.util.Date is outdated. Use LocalDate

2022-02-22 06:17 UTC, viktarkolbik commented on pom.xml
> -    </dependencies>
Why do you need this dependency?

2022-02-22 06:23 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingResponseDTO.java
> +    private Object message;
Why object? Why not String?

2022-02-22 06:23 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingResponseDTO.java
> +    private Integer code;
code and status are useless here

2022-02-22 06:41 UTC, Apulatjonov commented on pom.xml
> -    </dependencies>
I tried to fix the error I was getting in workplaceService when pulled the project from main branch that time

2022-02-22 06:41 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(bookingService.updateBooking(bookingDto, id));
got you

2022-02-22 06:42 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingResponseDTO.java
> +    private Integer code;
ok

2022-02-22 06:42 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingResponseDTO.java
> +    private Object message;
I was giving "objects" itself not "objects.toString()", ok I will fix it

2022-02-23 07:29 UTC, gargatuma requested changes

2022-02-23 07:29 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/Booking.java
> +    private Date endDate;
add validation

2022-02-23 07:57 UTC, gargatuma requested changes

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
>      @GetMapping(path = "/{id}")
no need for path

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
>      @GetMapping(path = "/{id}")
just "/{id}"

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +                .orElseThrow(() -> new NotFoundException("There is no such booking", Booking.class, "bookingId"));
for field parameter pass just "id" not "bookingId"

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +                .orElseThrow(() -> new NotFoundException("There is no such booking", Booking.class, "bookingId"));
for field parameter pass just "id" not "bookingId"

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +                .orElseThrow(() -> new NotFoundException("There is no such booking", Booking.class, "bookingId"));
for field parameter pass just "id" not "bookingId"

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +        return Boolean.TRUE;
you can return just "true" and java autoboxing wil work

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingDTO.java
> +}
missing validations

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +    public ResponseEntity<?> addBooking(@RequestBody BookingDTO bookingDTO) {
add validation

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
> +    public ResponseEntity<?> updateBooking(@PathVariable UUID id, @RequestBody BookingDTO bookingDto) {
add validation

2022-02-23 07:57 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +            throw new ConflictException("Conflict", Booking.class, "booking");
for field parameter pass just "id" not "bookingId"

2022-02-23 09:57 UTC, Apulatjonov commented on src/main/resources/db/changelog/changeset/10-drop-wrong-end-keyword-booking-table.yaml
> +            columnName: end
I did

2022-02-23 09:58 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
>      @GetMapping(path = "/{id}")
it is autogenerated

2022-02-23 13:10 UTC, viktarkolbik submitted a review, later dismissed

2022-02-23 13:12 UTC, viktarkolbik commented on pom.xml
> -    </dependencies>
Still don't understand what type of the error this dependency fixes.

2022-02-23 13:29 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +        bookings.forEach(booking -> {
u can use stream map here

2022-02-24 13:43 UTC, gargatuma requested changes

2022-02-24 16:06 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +            throw new ConflictException("Conflict", Booking.class, "booking");
could not get?!

2022-02-24 16:06 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingDTO.java
> +    private UUID userId;
ok

2022-02-24 16:06 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +    public BookingService(BookingRepository bookingRepository, UserRepository userRepository, WorkplaceRepository workplaceRepository, WaitingListService waitingListService, BookingMapper bookingMapp
ok

2022-02-24 16:06 UTC, Apulatjonov commented on src/main/java/com/exadel/coolDesking/booking/BookingService.java
> +    private final WorkplaceRepository workplaceRepository;
ok

2022-02-25 11:10 UTC, viktarkolbik approved these changes

2022-02-25 11:13 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/booking/BookingController.java
>      @GetMapping(path = "/{id}")
simplify your code
```suggestion
    @GetMapping("/{id}")/
```

2022-02-25 14:05 UTC, gargatuma approved these changes

2022-02-25 14:06 UTC, merged