PR from vacation branch
ohalushchak-exadel/internship-team4 pull request #28
Opened 2022-02-20 18:19 UTC by MurodjonMukhamadaliev

CRUD completed and tested

2022-02-21 07:18 UTC, gargatuma requested changes

2022-02-21 07:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/vacation/VacationController.java
> +    @PostMapping("/create")
No need for '/create', just use PostMapping

2022-02-21 07:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/vacation/VacationController.java
> +    @PutMapping("/edit/{id}")
just '/{id}' no need for '/edit'

2022-02-21 07:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/vacation/VacationController.java
> +    @DeleteMapping("/delete/{id}")
just '/{id}' no need for '/delete'

2022-02-21 07:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/vacation/VacationCreateDto.java
> +   // private UUID id;
remove unnecessary comments

2022-02-21 07:18 UTC, gargatuma commented on src/main/resources/application.properties
> +spring.datasource.password=1199
don't change username and password

2022-02-21 07:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceController.java
>      @GetMapping("/workplace/{workplace_id}")
Why changed this class?

2022-02-22 17:13 UTC, gargatuma requested changes

2022-02-22 17:21 UTC, gargatuma submitted a review, later dismissed

2022-02-22 18:16 UTC, ohalushchak-exadel requested changes

2022-02-22 18:16 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/vacation/VacationService.java
> +    public UUID createVacation(VacationCreateDto vacationCreateDto) {
return dto with the `id` field

2022-02-23 12:02 UTC, ohalushchak-exadel requested changes

2022-02-23 12:02 UTC, ohalushchak-exadel commented on src/main/resources/application.properties
> +spring.datasource.password=1199
^ @MurodjonMukhamadaliev

2022-02-23 13:05 UTC, ohalushchak-exadel approved these changes

2022-02-23 13:09 UTC, viktarkolbik approved these changes

2022-02-23 13:11 UTC, merged