Workplace
ohalushchak-exadel/internship-team4 pull request #4
Opened 2022-02-09 16:09 UTC by TokhirjonSoliev

workplace CRUD done and security enabled.

2022-02-10 09:13 UTC, ohalushchak-exadel requested changes

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            return new Response("Column is missing", 400);
your `WorkplaceDto` should have `@NotNull` annotations on fields instead of this

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    boolean existsByWorkplaceNumber(@NotNull Integer workplaceNumber);
`@NotNull` is not needed here

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return new Response("There is no such a workplace", 404);
you shouldn't think and work with the response http statuses in the services. This is not any different from using ResponseEntity

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        workplaceRepository.save(workplace);
use model mapper for this http://modelmapper.org/ (see my sample app for a simple example)

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        workplaceRepository.save(workplace);
model mapper

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            return new Response("There is no such a map", 404);
same with the responses

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return new Response("Successfuly deleted", 200);
same with the responses

2022-02-10 09:13 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/03-create-workplace-table.yaml
> +                  type: varchar(20)
since this changeset is already in master, you no longer can modify it.
create new changesets which drop the `is_vip` column and add `type` and `status` columns

2022-02-10 10:10 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        workplaceRepository.save(workplace);
[Or MapStruct](https://mapstruct.org). Be able to explain your choise.

2022-02-10 11:20 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/workspace/Workplace.java
> +    @Column(nullable = false)
This @Column annotation doesn't have **name** attribute.

2022-02-10 11:30 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            return new Response("There is no such a map", 404);
You can move all custom validations into separate method.

2022-02-10 17:19 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceController.java
> +     * @return
should I write something there? This is commentary and I thought there should be nothing after return.

2022-02-10 17:31 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return new Response("There is no such a workplace", 404);
In this case, What can I return?

2022-02-10 17:32 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        boolean workplaceNumber = workplaceRepository.existsByWorkplaceNumber(workplaceDto.getWorkplaceNumber());
ok I will try to select more readable and meaningfull names

2022-02-10 17:33 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        workplaceRepository.save(workplace);
Ok, I am using mapper and changing my code.

2022-02-10 17:36 UTC, TokhirjonSoliev commented on src/main/resources/db/changelog/changeset/03-create-workplace-table.yaml
> +                  type: varchar(20)
ok I will create new changeset for workplace but what about db.changelog-master.yaml? should I update it or create new one?

2022-02-10 17:40 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/Workplace.java
> +    @Column(nullable = false)
I thought that If I am going to save variable name at DB like what I write variable name in entity, then It is needless to write name in @Column but If I need to save it with another name, then I need to write. What do you think name always should be written in @Column?

2022-02-14 09:39 UTC, ohalushchak-exadel requested changes

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/response/Response.java
> +public class Response {
yes, you need to return workplace

and you still don't need this class, delete it

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/exception/ConflictException.java
> +    private final Integer status;
you don't need status here. conflict will always be 409

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/exception/ConflictException.java
> +    private final Integer status;
better add type and field

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/exception/NotFoundException.java
> +    private final Integer status;
you don't need status here. it will always be 404
better add entity type

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/Workplace.java
> +    @Column(name = "workplace_number", unique = true)
it's unique withing the office, right? `unique = true` is used when this column is unique across the whole table. remove it

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceController.java
> +    @PostMapping("/floorPlan/floorPlan_id/workplace")
...`{floorPlan_id}`...

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    List<Workplace> findByFloorPlan_Office_Id(UUID floorPlan_office_id);
name params according to the java style
`officeId` will be sufficient  as a param name

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    Optional<Workplace> findByFloorPlan_Office_IdAndId(UUID floorPlan_office_id, UUID id);
name params according to the java style
`officeId` will be sufficient  as a param name

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    boolean existsByFloorPlan_Office_IdAndWorkplaceNumber(UUID floorPlan_office_id, Integer workplaceNumber);
name params according to the java style
`officeId` will be sufficient  as a param name

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/resources/application.properties
> +spring.datasource.password=tokhir1799
agree with the team on a single username/password which everyone will be using locally to avoid changing this file in such cases

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/08-drop-is_vip-workplace-column.yaml
> +      id: drop-workplace-table
more like `drop_is_vip_column_of_workplace-table`

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/09-add-columns-workplace.yaml
> +      id: add-workplace-table
`add_type_and_status_columns_to_workplace_table`

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/09-add-columns-workplace.yaml
> +      id: add-workplace-table
and add a precondition that checks that those columns don't exist yet

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/09-add-columns-workplace.yaml
which columns? add them to the file name

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return optionalWorkplace.orElse(null);
orElse throw your new `NotFoundException`

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        Optional<Workplace> optionalWorkplace = workplaceRepository.findByFloorPlan_Office_IdAndId(office_id, workplace_id);
orElse throw your new `NotFoundException`

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            Workplace savedWorkplace = workplaceRepository.save(workplace);
use mapper here

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            throw new ConflictException("File size exceeds 2 MB", 400);
[See the Tuning File Upload Limits Section](https://spring.io/guides/gs/uploading-files/)

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            throw new ConflictException("Wrong format", 409);
this is a `BadRequest`, not 'Conflict'

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                workplaces.add(workplace);
move into a separate method

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                workplaces.add(workplace);
move into a separate method

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                    throw new ConflictException("Number is not unique within the map", 400);
which number exactly?

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                    throw new NotFoundException("There is no such a floor plan", 404, "floorPlanId");
which floor plan exactly?

also you can move this validation to the beginning of your method (and remove the copy from csv reader)

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                }
same as for xls

2022-02-14 09:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return "created";
make it void

2022-02-14 10:23 UTC, TokhirjonSoliev commented on src/main/resources/application.properties
> +spring.datasource.password=tokhir1799
I have used my own DB in order to check whether my work is working

2022-02-14 10:51 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            Workplace savedWorkplace = workplaceRepository.save(workplace);
How can use mapper in this case?
I am editing exisiting workplace to the new one. How can I implement mapper to this case?

2022-02-14 18:03 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    List<Workplace> findByFloorPlan_Office_Id(UUID office_id);
`(UUID officeId)`

2022-02-14 18:03 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    Optional<Workplace> findByFloorPlan_Office_IdAndId(UUID office_id, UUID id);
`(UUID officeId...`

2022-02-14 18:03 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceRepository.java
> +    boolean existsByFloorPlan_Office_IdAndWorkplaceNumber(UUID office_id, Integer workplaceNumber);
`(UUID officeId...`

2022-02-14 18:05 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public List<Workplace> getWorkPlaces(UUID office_id) {
return list of `WorkplaceResponseDto`

2022-02-14 18:05 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public Workplace getWorkPlace(UUID office_id, UUID workplace_id) {
return WorkplaceResponseDto

2022-02-14 18:06 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        if (!contentType.equals("xls") && !contentType.equals("csv")) {
contentType can be `null`

2022-02-14 18:07 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            inputStream = file.getInputStream();
use `try-with-resources`

2022-02-14 18:19 UTC, gargatuma commented
good job

2022-02-14 18:20 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            throw new NotFoundException("There is no such a workplace", Workplace.class, "office_id and workplace_id");
orElseThrow

2022-02-14 18:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        return workplaceRepository.findByFloorPlan_Office_IdAndId(office_id, workplace_id).orElseThrow(() -> new NotFoundException("There is no such a workplace", Workplace.class, "office_id and work
include actual Ids in the 'search'

2022-02-14 18:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            throw new NotFoundException("There is no such a workplace", Workplace.class, "office_id and workplace_id");
include actual Ids in the 'search'

2022-02-14 18:23 UTC, gargatuma requested changes
some changes needs to be made

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                throw new ConflictException("Column is mising", Workplace.class, "Column");
*mising -> missing

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        if (!contentType.equals("xls") && !contentType.equals("csv")) {
contentType.equals could throw NullPointerException

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        if (!optionalWorkplace.isPresent()) {
!optionalWorkplace.isPresent() could be replaced with optionalWorkplace.isEmpty()

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            if (!optionalFloorPlan.isPresent()) {
!optionalWorkplace.isPresent() could be replaced with optionalWorkplace.isEmpty()

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            if (!optionalFloorPlan.isPresent()) {
!optionalWorkplace.isPresent() could be replaced with optionalWorkplace.isEmpty()

2022-02-14 18:23 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceCreateDto.java
> +    @ToString.Exclude
ToString.Eclude should be removed from all fields

2022-02-14 18:23 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            WorkplaceCreateDto workplaceCreateDto = new WorkplaceCreateDto();
move below the 'skip' part

2022-02-14 18:32 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    private List<Workplace> readFromXls(InputStream inputStream, UUID office_id, UUID floorPlan_id) throws IOException {
officeId, floorPlanId

2022-02-14 18:32 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public void addWorkplace(MultipartFile file, UUID office_id, UUID floorPlan_id) {
officeId, floorPlanId

2022-02-14 18:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public Workplace getWorkPlace(UUID office_id, UUID workplace_id) {
officeId, workplaceId

2022-02-14 18:33 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public List<Workplace> getWorkPlaces(UUID office_id) {
officeId

2022-02-14 18:36 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +                throw new ConflictException(workplaceCreateDto.getWorkplaceNumber() + " is not unique within the " + floorPlan_id, Workplace.class, "Integer");
"Integer" is not a field
`within the` what?
`within the floor plan .. `

2022-02-14 18:36 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/09-add-type-and-status-columns-workplace.yaml
> +              columnName: status
bad formatting

2022-02-14 18:38 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/09-add-type-and-status-columns-workplace.yaml
> +                    nullable: false
since the table already exists and technically can contain some data, you can't just add new not nullable columns. You need to set the default value

2022-02-14 18:38 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceController.java
> +}
missing new line at the end of file

2022-02-14 18:59 UTC, TokhirjonSoliev commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public List<Workplace> getWorkPlaces(UUID office_id) {
you mean like that
![image](https://user-images.githubusercontent.com/88486017/153928551-b3f5dbec-8f2b-4721-9d5f-613379ef0864.png)

2022-02-14 19:03 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +    public List<Workplace> getWorkPlaces(UUID office_id) {
yes, but use a stream + collector instead

2022-02-15 10:20 UTC, ohalushchak-exadel commented on pom.xml
> +            <version>5.1.0</version>
update to [5.2.0](https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml/5.2.0)

2022-02-15 10:26 UTC, TokhirjonSoliev commented on pom.xml
> +            <version>5.1.0</version>
done, anything else?

2022-02-15 10:45 UTC, ohalushchak-exadel requested changes
project cannot be built

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/Workplace.java
> +    @NotNull()
remove `()`

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceController.java
> +@RequestMapping(path = "/office/{office_id}")
@gargatuma no, it's good

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +        assert contentType != null;
throw bad request exception if content type is null

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            if (optionalFloorPlan.isEmpty()) {
orElseThrow

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
> +            inputStream = file.getInputStream();
`try-with-resources`

2022-02-15 10:45 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/09-add-type-and-status-columns-workplace.yaml
> +        - onFail: MARK_RAN
duplicated `onFail`

2022-02-15 18:26 UTC, ohalushchak-exadel requested changes

2022-02-15 18:26 UTC, ohalushchak-exadel commented on mvnw.cmd
> +@REM JAVA_HOME = C:\Users\John Terry\.jdks\openjdk-17.0.1
this file should not be changed. Remove this line

2022-02-15 18:26 UTC, ohalushchak-exadel commented on pom.xml
> +		<java.version>11</java.version>
why?

2022-02-15 18:26 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/workspace/WorkplaceService.java
>              throw new BadRequestException("Wrong format", Workplace.class, "column");
` BadRequestException("Invalid ContentType", Workplace.class, "contentType");`

2022-02-15 19:05 UTC, TokhirjonSoliev commented on pom.xml
> +		<java.version>11</java.version>
because, I had problems with 17, so I changed it to 11. ok?

2022-02-15 20:02 UTC, ohalushchak-exadel approved these changes

2022-02-16 03:42 UTC, gargatuma approved these changes

2022-02-16 03:42 UTC, merged