Floor plan
ohalushchak-exadel/internship-team4 pull request #40
Opened 2022-02-26 03:49 UTC by shohruhsadullayev

2022-02-28 09:18 UTC, gargatuma requested changes

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/CoolDeskingApplication.java
> -
don't change this class

2022-02-28 09:18 UTC, gargatuma commented on src/main/resources/application.properties
> +spring.datasource.password=123
don't change database connection properties

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/user/User.java
> +@Table(name = "user")
this will give an error while inserting to database. Rollback this change

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/Office.java
> +import java.util.List;
unused import

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanResponseDTO.java
> +    public FloorPlanResponseDTO(FloorPlan res) {
remove his constructor and use mapper where this constructor is used

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanResponseDTO.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
Why do u need this?

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +    void deleteFloorPlan(UUID id);
No need for interface

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> -
This field is needed

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +    @Column(name = "office_id", insertable = false, updatable = false)
add validation

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> -        = @UniqueConstraint(columnNames = {"office_id", "floor"}))
This is required otherwise if u insert false data it will give internal server error

2022-02-28 09:18 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/ControllerAdvisor.java
> +}
Exception Advice is already completed by Husan in a separate PR

2022-03-07 14:54 UTC, gargatuma requested changes

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanMapper.java
> +}
missing new line at the end of file

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> -    @JoinColumn(name = "office_id", referencedColumnName = "id")
referencing column should be defined explicitly

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/office/OfficeRepository.java
> +    Office getOfficeById(UUID id);
you should use Optional wrapper for return type

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if (office == null) {
getOfficeById should return Optional. And use IsEmpty or OrElseThrow for better readability

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanCreateResponseDTO.java
> +@AllArgsConstructor
separate imports from annotations

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanMapper.java
> +@Component
separate imports from annotations

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if(floorPlanRepository.findByFloorAndOfficeId(floorPlanUpdateDTO.getFloor(), floorPlan.getOffice().getId()).isPresent()) {
please make this line more readable by introducing additional variable

2022-03-07 14:54 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if(floorPlanRepository.findByFloorAndOfficeId(floorPlanUpdateDTO.getFloor(), floorPlan.getOffice().getId()).isPresent()) {
also using exists could improve the performance of application

2022-03-07 16:57 UTC, ohalushchak-exadel requested changes
Address @gargatuma 's comments as well

2022-03-07 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +       return ResponseEntity.status(HttpStatus.CREATED).body(floorPlanService.updateFloorPlan(floorPlanUpdateDTO, id));
OK, not CREATED

2022-03-07 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeRepository.java
> +    Optional<Office> getOfficeById(UUID id);
you don't need this method. Change `JpaRepository` to `CrudRepository` and use `findById()` method

2022-03-07 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +        if (office.isEmpty()) {
use `orElseThrow()` instead of `office.isEmpty()`

2022-03-07 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/Office.java
> +
remove this empty line and the line above

2022-03-08 14:25 UTC, ohalushchak-exadel requested changes

2022-03-08 14:25 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(floorPlanService.createFloorPlan(floorPlanCreateDTO));
CREATED, not OK

2022-03-08 14:25 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +        }
this check will always throw ConflictException when you're updating the floor plan without changing the floor.
you need `existsByFloorAndOfficeIdNot`

2022-03-09 07:48 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> -        = @UniqueConstraint(columnNames = {"office_id", "floor"}))
@gargatuma it's reformatted, not removed

2022-03-10 11:50 UTC, gargatuma requested changes

2022-03-10 11:50 UTC, gargatuma commented on src/main/resources/application.properties
> +spring.servlet.multipart.max-file-size=2MB
don't change this file. Rollback changes

2022-03-16 12:48 UTC, gargatuma submitted a review, later dismissed

2022-03-17 13:01 UTC, gargatuma approved these changes

2022-03-17 13:10 UTC, gargatuma approved these changes

2022-03-17 13:11 UTC, ohalushchak-exadel approved these changes

2022-03-17 13:12 UTC, merged