bot initial structure
ohalushchak-exadel/internship-team4 pull request #45
Opened 2022-03-03 11:53 UTC by gargatuma

Created architecture of bot for further divison of tasks among interns

2022-03-03 12:24 UTC, ohalushchak-exadel requested changes

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/config/botConfig.java
> +    private final String URL = System.getenv("URL");
https://www.baeldung.com/spring-value-annotation

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/config/botConfig.java
> +    private final String URL = System.getenv("URL");
use more meaningful names for the env vars like `TELEGRAM_WEBHOOK_URL` and `TELEGRAM_INTERNAL_URL`

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/HotDeskingBot.java
> +    private final String BOT_TOKEN = System.getenv("BOT_TOKEN");
move to constructor + https://www.baeldung.com/spring-value-annotation

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/BotController.java
> +    @PostMapping("/")
any chance to use another mapping? like `/api/telegram-bot`

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/HotDeskingBot.java
> +        return "exadel";
at least make it constant

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +                this.handlers.put(handler.getHandlerStateName(), handler));
try using `.stream().collect(toMap(...))`

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            System.out.println(response.getMethod());
use logger

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("DATA: " + query.getData());
`log.info("DATA: {}", query.getData());`

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("TelegramId: " + telegramId);
same as with data DATA

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("UserState: " + user.getUserState());
same as with data DATA

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("Handler: " + handler);
same as with data DATA

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("Handler: " + handler);
are you sure any of this data is not sensitive and can be logged?

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +        if (update.hasCallbackQuery()) {
can be moved into a separate method

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/config/botConfig.java
> +            return null;
maybe you want to fail the application startup if the bot can't be loaded ? You need to rethrow the exception then.

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/config/botConfig.java
> +            e.printStackTrace();
log it properly

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/dto/BotResponseDto.java
> +public class BotResponseDto {
stateful components should not be singletons. why is it a component anyway?

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/exception/BotExceptionAdvice.java
> +                );
`log.warn("{}; Telegram Id: {}; Class: {}",exception.getMessage(), exception.getTelegramId(), exception.getType());`

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/exception/BotExceptionAdvice.java
> +        );
same as in handleBotNotFound

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/city/CityHandler.java
> +            return service.backToMainMenu(messageId, chatId);
parenthesis

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/country/CountryHandler.java
> +            return service.backToMainMenu(messageId, chatId);
parenthesis

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/country/CountryHandlerService.java
> +                    telegramId);
parenthesis

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/city/CityHandlerService.java
> +                    telegramId);
parenthesis

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/main/MainMenuHandler.java
> +            return service.showListOfCountries(messageId, chatId);
parenthesis

2022-03-03 12:24 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/util/MarkupService.java
> +            keyboardButtons.add((List.of(oneButton(data.get(i), data.get(i)))));
parenthesis

2022-03-04 09:26 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            log.info("Handler: " + handler);
I will remove them. I used them just for debugging.

2022-03-04 18:15 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/bot/HotDeskingBot.java
> +    public HotDeskingBot(SetWebhook setWebhook, UpdateReceiver updateReceiver, String BOT_TOKEN, String BOT_USERNAME, String BOT_PATH) {
```suggestion
    public HotDeskingBot(SetWebhook setWebhook, UpdateReceiver updateReceiver, String token, String username, String path) {
```
Don't use uppercase for method parameters

2022-03-04 18:23 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +        log.info("Handler: {}", handler);
your handler classes don't implement toString method. This log will print hashCode, it is senseless information.

2022-03-05 03:43 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +        log.info("Handler: {}", handler);
line 51 will print out Handler class name, and that's what I want. I just want to see which handler was used for particular request)

2022-03-05 14:19 UTC, ohalushchak-exadel requested changes

2022-03-05 14:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/HotDeskingBot.java
> +        this.BOT_PATH = BOT_PATH;
you're not using params here :)

2022-03-05 14:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/config/botConfig.java
> +            @Value("${TELEGRAM_BOT_PATH}") String TELEGRAM_BOT_PATH) throws TelegramApiException {
use camelCase to name method params

2022-03-05 14:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +        log.info(response.getMethod().toString());
these should be `debug` - change later

2022-03-06 14:25 UTC, ohalushchak-exadel approved these changes

2022-03-06 17:42 UTC, merged