bot upgrade by Husan
ohalushchak-exadel/internship-team4 pull request #50
Opened 2022-03-08 19:15 UTC by KhusanKholmatov

solved some problems, re-starting, and BACK button

2022-03-09 12:22 UTC, ohalushchak-exadel requested changes

2022-03-09 12:22 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            str+=","+data.split(",")[i];
1. Do you really want the the first character of the string to be `,`?
2. When you need to concat strings in a loop it's better to use `StringBuilder`
3. You really can rewrite this to do `data.split(",")` only once
4. You also can use `String.join()` method

2022-03-09 15:35 UTC, KhusanKholmatov commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +            str+=","+data.split(",")[i];
ok

2022-03-11 11:17 UTC, ohalushchak-exadel requested changes

2022-03-11 11:17 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +        int len = data.split(",").length;
introduce a variable for `data.split(",")` and use it to get length and in the loop

2022-03-11 13:23 UTC, closed without merging