ReportResponseDto created.
ohalushchak-exadel/internship-team4 pull request #58
Opened 2022-03-15 11:12 UTC by TokhirjonSoliev

2022-03-15 15:52 UTC, gargatuma requested changes

2022-03-15 15:52 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/report/RepostResponseDto.java
> +    private User user;
UserDto instead of User

2022-03-17 15:43 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/report/ReportResponseDtos.java
> +    private String status;
according to the doc, you need a `full` field. code and status should not be a part of response body

2022-03-18 04:42 UTC, gargatuma approved these changes

2022-03-18 04:42 UTC, merged