booking ready by Husan
ohalushchak-exadel/internship-team4 pull request #61
Opened 2022-03-18 21:06 UTC by khusanKholmatov

2022-03-19 16:11 UTC, ohalushchak-exadel requested changes

2022-03-19 16:11 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/util/MarkupService.java
> +                    day.setText(k+"");
Integer.toString()

2022-03-19 16:11 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/util/MarkupService.java
> +                    day.setText(k+"");
you can use `date.getDayOfMonth()` instead of `k`

2022-03-19 16:14 UTC, ohalushchak-exadel commented
@gargatuma please, take a look as well

2022-03-24 08:39 UTC, ohalushchak-exadel requested changes

2022-03-24 08:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/oneDayBooking/OneDayBookingHandlerService.java
> +        final int MAX_MONTH = 3;
this should be a constant field in the class

2022-03-24 08:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/handler/recurringBooking/RecurringDaysBookingHandlerService.java
> +        final int MAX_WEEKS = 13;
this should be a constant field in the class

2022-03-24 08:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/util/MarkupService.java
> +        List<String> days = new ArrayList<>(List.of("M", "T", "W", "T", "F", "S", "S"));
you don't need `new ArrayList<>`

2022-03-24 08:39 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/bot/util/MarkupService.java
> +        int k=1;
it's not used anymore

2022-03-24 09:38 UTC, gargatuma requested changes

2022-03-24 09:38 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/bot/dto/BookingDateIdDto.java
> +    private UUID bookingBotId;
change name to incompleteBookingId

2022-03-24 09:38 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/bot/UpdateReceiver.java
> +import org.telegram.telegrambots.meta.api.methods.updatingmessages.DeleteMessage;
remove unused imports

2022-03-24 11:25 UTC, ohalushchak-exadel approved these changes

2022-03-24 11:48 UTC, gargatuma approved these changes

2022-03-24 11:48 UTC, merged