delete-office by Husan
ohalushchak-exadel/internship-team4 pull request #62
Opened 2022-03-18 22:44 UTC by khusanKholmatov

2022-03-19 15:17 UTC, ohalushchak-exadel requested changes

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(officeService.deleteOffice(id));
just return 204 http code with no response body

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeDeletedDto.java
> +public class OfficeDeletedDto {
you don't need it

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeService.java
> +    public OfficeDeletedDto deleteOffice(UUID id) {
void

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/user/UserService.java
> +    public void deleteUserWorkplaceId(List<User> userList){
`deleteUserPreferredWorkplaceId` maybe?

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/24-drop-office_id-foreign-key-adding-new_one-in-floor-plan.yaml
> +            constraintName: fk_floor_plan_office2
why not just `fk_floor_plan_office`?

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/24-drop-office_id-foreign-key-adding-new_one-in-floor-plan.yaml
> +            deleteCascade: true
`addForeignKeyConstraint` does not support `deleteCascade` attribute.

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/25-drop-floor_plan_id-foreign-key-adding-new_one-in-workplace.yaml
> +            deleteCascade: true
`addForeignKeyConstraint` does not support `deleteCascade` attribute.

2022-03-19 15:17 UTC, ohalushchak-exadel commented on src/main/resources/db/changelog/changeset/25-drop-floor_plan_id-foreign-key-adding-new_one-in-workplace.yaml
> +            constraintName: fk_workplace_floor_plan2
why not just `fk_workplace_floor_plan`

2022-03-24 11:37 UTC, khusanKholmatov commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(officeService.deleteOffice(id));
but, i have to return id, and message according to Google Doc

2022-03-24 12:02 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/office/OfficeController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(officeService.deleteOffice(id));
that doc is pretty bad, unfortunately

2022-03-24 12:02 UTC, ohalushchak-exadel approved these changes

2022-03-24 12:06 UTC, merged