Shohruh
ohalushchak-exadel/internship-team4 pull request #8
Opened 2022-02-10 13:05 UTC by shohruhsadullayev

2022-02-10 14:08 UTC, ohalushchak-exadel requested changes
remove gradle files
reformat code 
address comments

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +            floorPlanRepository.save(floorPlan);
after the entity is saved use the result returned from the `save()` method

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +}
reformat

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        floorPlanRepository.save(floorPlan);
after the entity is saved use the result returned from the `save()` method

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        floorPlan.setWorkplaceCount(request.getWorkplaceCount());
use mapper

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanService.java
> +public interface FloorPlanService {
you don't need it

2022-02-10 14:08 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanRepository.java
> +    FloorPlan getFloorPlanById(UUID id);
it's a copy of a default getById() method. Remove it. And in your case it would make more sense to use findById() which returns Optional

2022-02-10 14:11 UTC, ohalushchak-exadel commented
And name this Pull request properly

2022-02-11 05:41 UTC, viktarkolbik commented on src/main/java/com/exadel/coolDesking/office/OfficeRepository.java
> +import org.springframework.data.jpa.repository.Query;
Extra import

2022-02-11 06:27 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +    private  FloorPlanService floorPlanService;
I got you

2022-02-11 06:32 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +    public FloorPlan createNewFloorPlan(@RequestBody CreateFloorPlanRequest request)
Why we need @Valid annotation althoug we did not use validation in CreateFloorPlanRequest class ?

2022-02-11 06:34 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +        return "Deleted Successfully";
Ok

2022-02-11 06:39 UTC, shohruhsadullayev commented on src/main/resources/application.properties
> +spring.datasource.password=123
Do we have a common database?

2022-02-11 06:44 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +
its old code, and I changed it

2022-02-11 06:55 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/dto/CreateFloorPlanRequest.java
> +public class CreateFloorPlanRequest {
why need it?

2022-02-11 06:59 UTC, shohruhsadullayev commented on src/main/resources/application.properties
> +spring.datasource.password=123
if we have server, tell me and I'll connect with it, but I can't change my login and password, because I have more project in this.

2022-02-11 07:00 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +            throw new NullPointerException("Office is null");
ok

2022-02-14 18:40 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/dto/CreateFloorPlanRequest.java
> +public class CreateFloorPlanRequest {
so Sping/Hibernate can validate the request for us

2022-02-14 18:41 UTC, ohalushchak-exadel commented on src/main/resources/application.properties
> +spring.datasource.password=123
you can just create a new user and grant it access to the database

2022-02-16 18:21 UTC, gargatuma requested changes
mostly all files should be formatted correctly

2022-02-16 18:21 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlan.java
> +    private UUID officeId;
Why do we need separate officeId field?

2022-02-16 18:21 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if(!floorPlanRepository.findByFloorAndOfficeId(floorPlan.getFloor(), floorPlan.getOfficeId()).isPresent()){
!isPresent() can be replaced with is isEmpty()

2022-02-16 18:21 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if(!floorPlanRepository.findByFloorAndOfficeId(floorPlan.getFloor(), floorPlan.getOfficeId()).isPresent()){
is it possible to replace findByFloorAndOfficeId() by existsByFloorAndOfficeId()?

2022-02-16 18:21 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +            return null;
!isPresent() can be replaced with is isEmpty()

is it possible to replace findByFloorAndOfficeId() by existsByFloorAndOfficeId()?

2022-02-16 18:21 UTC, gargatuma commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +            FloorPlan floorPlan1 = floorPlanRepository.findById(id).get();
You should check whether FloorPlan with given id exists. Also Optional.get() is used without isPresent.

2022-02-18 22:25 UTC, ohalushchak-exadel requested changes
rebase or pull the latest changes from `main` into your branch

2022-02-21 16:57 UTC, ohalushchak-exadel requested changes

2022-02-21 16:57 UTC, ohalushchak-exadel commented on pom.xml
> +		</dependency>
not needed - already present

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +    public FloorPlanDTO createFloorPlan(@RequestBody FloorPlan floorPlan){
Create a separate DTO for create/update request body. You don't want clients to be able to pass their `id` in the `create` request

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +        floorPlanService.deleteFloorPlan(id);
return 204 http status

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +        return floorPlanService.createFloorPlan(floorPlan);
return 201 http status and an object with id of the created entity

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +                throw new NotFoundException("Office not found with this id: " + floorPlan.getOfficeId(), FloorPlan.class, "id");
add parenthesis

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +                throw new NotFoundException("Office not found with this id: " + floorPlan.getOfficeId(), FloorPlan.class, "id");
not `"id"` but `"officeId"`

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +                        " already exists in " + office.getName() + " office", FloorPlan.class, "id");
not `"id"` but `"floor"`

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        return floorPlanRepository.findById(id).orElseThrow(() -> new NotFoundException("The requested map "+id+" doesn't exist", FloorPlan.class, "id"));
move orElseThrow to a new line

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        if(floorPlanRepository.existsByFloorAndOfficeId(floorPlan.getFloor(), floorPlan.getOfficeId()).isPresent()){
this check won't work in case of updates. What if you're updating some parameters of the floor plan, but not its number?

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        FloorPlan floorPlan1 = floorPlanRepository.findById(id).get();
rename the variable
don't use numbers in the variable names unless they have some meaning

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        } catch (Exception e) {
it doesn't always mean that entity does not exist

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +        } catch (Exception e) {
better check if it exists before trying to delete it

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanDTO.java
> +public class FloorPlanDTO {
`FloorPlanResponseDTO`

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanDTO.java
> +    Boolean hasConfRoom;
missing `private` modifier

2022-02-21 16:57 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/coolDesking/floorPlan/mapper/FloorPlanMapper.java
> +        return floorPlan;
use ModelMapper

2022-02-22 08:36 UTC, shohruhsadullayev commented on pom.xml
> +		</dependency>
ok

2022-02-22 08:38 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanController.java
> +    public FloorPlanDTO createFloorPlan(@RequestBody FloorPlan floorPlan){
its old code, I have changed.

2022-02-22 08:56 UTC, shohruhsadullayev commented on src/main/java/com/exadel/coolDesking/floorPlan/FloorPlanServiceImpl.java
> +                throw new NotFoundException("Office not found with this id: " + floorPlan.getOfficeId(), FloorPlan.class, "id");
ok

2022-02-26 03:47 UTC, closed without merging